---
networks:
  frontend:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
    devices:
      - /dev/ttyACMO
    privileged: true
    labels:
      traefik.enable: "true"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
      traefik.http.services.homeassistant.loadbalancer.server.scheme: "http"
      traefik.http.routers.homeassistant-https.entrypoints: "https"
      traefik.http.routers.homeassistant-https.rule: "Host(`homeassistant.sheetgenius.app`)"
      traefik.http.routers.homeassistant-https.tls: "true"
      traefik.http.routers.homeassistant-https.tls.certresolver: "cloudflare"
    networks:
      - frontend
    restart: unless-stopped
