version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - TZ=Europe/Madrid
    user: "1000:1000"
    network_mode: 'host'
    volumes:
      - /path/to/config:/config  # TODO: Replace with the actual config path
      - /path/to/cache:/cache  # TODO: Replace with the actual cache path
      - type: bind
        source: /path/to/media  # TODO: Replace with actual media path
        target: /media
      - type: bind
        source: /path/to/media2  # TODO: Replace with actual second media path
        target: /media2
        read_only: true
    restart: 'unless-stopped'

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_password  # TODO: Set the database password
      - MYSQL_HOST=db
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /path/to/config:/config  # TODO: Replace with the actual config path
      - /path/to/data:/data  # TODO: Replace with the actual data path
    networks:
      - database
      - internal
    ports:
      - 443:443
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: linuxserver/mariadb
    container_name: db
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /path/to/config:/config  # TODO: Replace with the actual config path
    networks:
      - database
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment: 
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/data:/data  # TODO: Replace with the actual data path
    networks:
      - internal
    ports:
      - 9443:9443
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /path/to/config:/config  # TODO: Replace with the actual config path
      - /path/to/download:/downloads  # TODO: Replace with the actual download path
    networks:
      - internal
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "your_admin_password"  # TODO: Set the admin password
      PHOTOPRISM_ORIGINALS_LIMIT: 1000
      PHOTOPRISM_HTTP_COMPRESSION: "none"
      PHOTOPRISM_WORKERS: 1
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"
      PHOTOPRISM_DARKTABLE_PRESETS: "true"
      PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"
      PHOTOPRISM_FFMPEG_BUFFERS: "64"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "db:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "your_database_password"  # TODO: Set the database password
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
    user: "1000:1000"
    devices:
      - "/dev/video11:/dev/video11"
    volumes:
      - "/path/to/original/photo:/photoprism/originals/"  # TODO: Replace with the actual path
      - "/path/to/data:/photoprism/storage"  # TODO: Replace with the actual path
    networks: 
      - database
      - internal
    ports:
      - 2342:2342
    restart: unless-stopped
    depends_on: 
      - db

networks:
  database:
    name: database
    driver: bridge
  internal:
    name: internal
    driver: bridge
