---
- Networking:
    - FritzBox:
        href: http://192.168.82.1
        icon: avmfritzbox.svg
        description: gw-prod-1
        siteMonitor: http://192.168.82.1
        widget:
            type: fritzbox
            url: http://192.168.82.1
    - Pihole:
        href: https://pihole.sheetgenius.app
        icon: pi-hole.svg
        description: pihole-prod-1 on srv-prod-1
        widget:
            type: pihole
            url: https://pihole.sheetgenius.app
            key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Traefik:
        href: https://traefik.sheetgenius.app
        icon: traefik.svg
        description: traefik-prod-1 on srv-prod-1
        widget:
            type: traefik
            url: https://traefik.sheetgenius.app
            key: {{HOMEPAGE_VAR_TRAEFIK_KEY}}

- Storage:
    - Nexcloud:
        href: https://nextcloud.sheetgenius.app
        icon: nextcloud.svg
        description: nextcloud-prod-1 on srv-prod-1
        widget:
            type: nextcloud
            url: https://nextcloud.sheetgenius.app
            key: {{HOMEPAGE_VAR_NEXTCLOUD_KEY}}
    - Bittorrent:
        href: https://bittorrent.sheetgenius.app
        icon: si-bittorrent
        description: bittorrent-prod-1 on srv-prod-1
        widget:
            type: bittorrent
            url: https://bittorrent.sheetgenius.app
            key: {{HOMEPAGE_VAR_BITTORRENT_KEY}}
    
- Media:
    - Plex:
        href: https://plex.sheetgenius.app
        icon: plex.svg
        description: plex-prod-1 on srv-prod-1
        widget:
            type: plex
            url: https://plex.sheetgenius.app
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
    - Jellyfin:
        href: https://jellyfin.sheetgenius.app
        icon: jellyfin.svg
        description: jellyfin-prod-1 on srv-prod-1
        widget:
            type: jellyfin
            url: https://jellyfin.sheetgenius.app
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
        
- Management:
    - Portainer:
        href: https://portainer-demo-1.sheetgenius.app
        icon: portainer.svg
        description: portainer-demo-1 on srv-demo-1
        widget:
            type: portainer
            url: https://portainer-demo-1.sheetgenius.app
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Watchtower:
        href: https://watchtower.sheetgenius.app
        icon: watchtower.svg
        description: watchtower-prod-1 on srv-prod-1
        widget:
            type: watchtower
            url: https://watchtower.sheetgenius.app
            key: {{HOMEPAGE_VAR_WATCHTOWER_KEY}}
        
- Monitoring:
    - Prometheus:
        href: https://prometheus.sheetgenius.app
        description: prometheus-prod-1 on srv-prod-1
        icon: prometheus.svg
        server: srv-prod-1
        container: prometheus-prod-1
        widget:
            type: prometheus
            url: https://prometheus.sheetgenius.app
    - Grafana:
        href: https://grafana.sheetgenius.app
        description: grafana-prod-1 on srv-prod-1
        icon: grafana.svg
        server: srv-prod-1
        container: grafana-prod-1

- Security:
    - Authentik:
        href: https://authentik.sheetgenius.app
        description: authentik-prod-1 on kube-prod-1
        icon: authentik.png
        widget:
            type: authentik
            url: https://authentik.sheetgenius.app
            key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}}
    - Wireguard:
        href: https://wireguard.sheetgenius.app
        description: wireguard-prod-1 on srv-prod-1
        icon: wireguard.svg

- Automation:
    - Home Assistant:
        href: https://homeassistant.sheetgenius.app
        icon: home-assistant.svg
        description: homeassistant-prod-1 on srv-prod-7
        widget:
            type: homeassistant
            url: https://homeassistant.sheetgenius.app
            key: {{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}
            custom:
