---
- Networking:
    - FritzBox:
        href: http://192.168.82.1
        icon: avmfritzbox.svg
        description: gw-prod-1
        siteMonitor: http://192.168.82.1
        widget:
            type: fritzbox
            url: http://192.168.82.1
    - Pihole:
        href: http://pihole.localhost:8081/admin # https://pihole.sheetgenius.app
        icon: pi-hole.svg
        description: pihole on srv-prod-1
        container: pihole
        widget:
            type: pihole
            url: http://pihole.localhost:8081 # https://pihole.sheetgenius.app
            version: 5
            key: admin # {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Traefik:
        href: http://traefik.localhost:8080/dashboard/ # https://traefik.sheetgenius.app
        icon: traefik.svg
        description: traefik-prod-1 on srv-prod-1
        container: traefik
        widget:
            type: traefik
            url: http://traefik.localhost:8080 # https://traefik.sheetgenius.app
            username: admin # TODO
            password: admin # TODO

- Storage:
    - QNAP 462:
        href: http://<IP> # TODO
        icon: qnap.svg
        description: qnap-462 on srv-prod-1
        widget:
            type: qnap
            url: http://<IP> # TODO
            key: {{HOMEPAGE_VAR_QNAP462_KEY}}
    
- Media:
    - Plex:
        href: https://plex.sheetgenius.app
        icon: plex.svg
        description: plex-prod-1 on srv-prod-1
        widget:
            type: plex
            url: https://plex.sheetgenius.app
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
    - Jellyfin:
        href: https://jellyfin.sheetgenius.app
        icon: jellyfin.svg
        description: jellyfin-prod-1 on srv-prod-1
        widget:
            type: jellyfin
            url: https://jellyfin.sheetgenius.app
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
    - Sonarr:
        href: https://sonarr.sheetgenius.app
        icon: sonarr.svg
        description: sonarr-prod-1 on srv-prod-1
        widget:
            type: sonarr
            url: https://sonarr.sheetgenius.app
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - Radarr:
        href: https://radarr.sheetgenius.app
        icon: radarr.svg
        description: radarr-prod-1 on srv-prod-1
        widget:
            type: radarr
            url: https://radarr.sheetgenius.app
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - Lidarr:
        href: https://lidarr.sheetgenius.app
        icon: lidarr.svg
        description: lidarr-prod-1 on srv-prod-1
        widget:
            type: lidarr
            url: https://lidarr.sheetgenius.app
            key: {{HOMEPAGE_VAR_LIDARR_KEY}}
    - Readarr:
        href: https://readarr.sheetgenius.app
        icon: readarr.svg
        description: readarr-prod-1 on srv-prod-1
        widget:
            type: readarr
            url: https://readarr.sheetgenius.app
            key: {{HOMEPAGE_VAR_READARR_KEY}}
    - Bazarr:
        href: https://bazarr.sheetgenius.app
        icon: bazarr.svg
        description: bazarr-prod-1 on srv-prod-1
        widget:
            type: bazarr
            url: https://bazarr.sheetgenius.app
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}
    - Nexcloud:
        href: https://nextcloud.sheetgenius.app
        icon: nextcloud.svg
        description: nextcloud-prod-1 on srv-prod-1
        widget:
            type: nextcloud
            url: https://nextcloud.sheetgenius.app
            key: {{HOMEPAGE_VAR_NEXTCLOUD_KEY}}
    - Bittorrent:
        href: https://bittorrent.sheetgenius.app
        icon: si-bittorrent
        description: bittorrent-prod-1 on srv-prod-1
        widget:
            type: bittorrent
            url: https://bittorrent.sheetgenius.app
            key: {{HOMEPAGE_VAR_BITTORRENT_KEY}}
        
- Management:
    - Portainer:
        href: https://portainer.localhost:9443 # https://portainer.sheetgenius.app
        icon: portainer.svg
        description: portainer-demo-1 on srv-demo-1
        container: portainer
        widget:
            type: portainer
            url: https://portainer.localhost:9443 # https://portainer.sheetgenius.app
            env: 1
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Watchtower:
        href: http://localhost:8082 # https://watchtower.sheetgenius.app
        icon: watchtower.svg
        description: watchtower-prod-1 on srv-prod-1
        container: watchtower
        widget:
            type: watchtower
            url: http://localhost:8082 # https://watchtower.sheetgenius.app
            key: {{HOMEPAGE_VAR_WATCHTOWER_KEY}}
        
- Monitoring:
    - Prometheus:
        href: http://localhost:9090 # https://prometheus.sheetgenius.app
        description: prometheus on srv-prod-1
        icon: prometheus.svg
        container: prometheus
        widget:
            type: prometheus
            url: http://localhost:9090 # https://prometheus.sheetgenius.app
    - Grafana:
        href: http://localhost:3001 # https://grafana.sheetgenius.app
        description: grafana on srv-prod-1
        icon: grafana.svg
        container: grafana
        widget:
            type: grafana
            url: http://localhost:3001 # https://grafana.sheetgenius.app
            username: admin # TODO
            password: pEW*QdSUQvyvuxRH5x0wft&F # TODO

- Security:
    - Authentik:
        href: https://authentik.sheetgenius.app
        description: authentik-prod-1 on kube-prod-1
        icon: authentik.png
        container: authentik
        widget:
            type: authentik
            url: https://authentik.sheetgenius.app
            key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}}
    - Wireguard:
        href: https://wireguard.sheetgenius.app
        description: wireguard-prod-1 on srv-prod-1
        icon: wireguard.svg
        container: wireguard
        widget:
            type: wireguard
            url: https://wireguard.sheetgenius.app
            key: {{HOMEPAGE_VAR_WIREGUARD_KEY}}

- Automation:
    - Home Assistant:
        href: https://homeassistant.sheetgenius.app
        icon: home-assistant.svg
        description: homeassistant-prod-1 on srv-prod-7
        container: homeassistant
        widget:
            type: homeassistant
            url: https://homeassistant.sheetgenius.app
            key: {{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}
