---
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - frontend
      - backend
    pid: host
    restart: unless-stopped
