---
- Networking:
    - FritzBox:
        href: http://192.168.178.1
        icon: fritzbox.svg
        description: gw-prod-1
        siteMonitor: http://192.168.178.1
        widget:
            type: fritzbox
            url: http://192.168.178.1
    - PiHole:
        href: http://192.168.178.24/admin # https://pihole.sheetgenius.app
        icon: pi-hole.svg
        description: pihole-prod-1 on rpi-nico-small
        container: pihole
        widget:
            type: pihole
            url: http://192.168.178.24 # https://pihole.sheetgenius.app
            version: 6
            key: '{{HOMEPAGE_VAR_PIHOLE_KEY}}'
    - Traefik:
        href: https://traefik-dashboard.sheetgenius.app/
        icon: traefik.svg
        description: traefik on rpi-angel-1
        container: traefik
        widget:
            type: traefik
            url: http://traefik:8080

- Storage:
    - QNAP 462:
        href: http://192.168.178.48:8080/cgi-bin/ # TODO
        icon: qnap.svg
        description: qnap-462 on rpi-angel-1
        widget:
            type: qnap
            url: http://192.168.178.48:8080 # TODO
            username: '{{ HOMEPAGE_VAR_QNAP_USERNAME }}'
            password: '{{ HOMEPAGE_VAR_QNAP_PASSWORD }}'


- Management:
    - Portainer:
        href: https://portainer.sheetgenius.app
        icon: portainer.svg
        description: portainer-demo-1 on rpi-angel-1
        container: portainer
    - Watchtower:
        href: https://watchtower.sheetgenius.app
        icon: watchtower.svg
        description: watchtower-prod-1 on rpi-angel-1
        container: watchtower
        # widget:
        #     type: watchtower
        #     url: http://watchtower:8080
        #     key: {{HOMEPAGE_VAR_WATCHTOWER_KEY}}

- Monitoring:
    - Grafana:
        href: https://grafana.sheetgenius.app
        description: grafana on rpi-angel-1
        icon: grafana.svg
        container: grafana
        # widget:
        #     type: grafana
        #     url: https://grafana.sheetgenius.app
        #     username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
        #     password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - Prometheus:
        href: https://prometheus.sheetgenius.app
        description: prometheus on rpi-angel-1
        icon: prometheus.svg
        container: prometheus


- Security:
    - TailScale:
        href: https://tailscale.sheetgenius.app
        description: tailscale-prod-1 on rpi-angel-1
        icon: tailscale.svg
        container: tailscale
        # widget:
        #     type: tailscale
        #     deviceid: {{ HOMEPAGE_VAR_TAILSCALE_DEVICEID }}
        #     key: {{ HOMEPAGE_VAR_TAILSCALE_KEY }}

- Automation:
    - Home Assistant:
        href: https://homeassistant.sheetgenius.app
        icon: home-assistant.svg
        description: homeassistant-prod-1 on rpi-angel-1
        container: homeassistant
        # widget:
        #     type: homeassistant
        #     url: https://homeassistant.sheetgenius.app
        #     key: {{ HOMEPAGE_VAR_HOMEASSISTANT_KEY }}
        #     custom:
        #         - state: sensor.total_power

- Media:
    - Plex:
        href: https://plex.sheetgenius.app
        icon: plex.svg
        description: plex-prod-1 on rpi-angel-1
        # widget:
        #     type: plex
        #     url: https://plex.sheetgenius.app
        #     key: {{HOMEPAGE_VAR_PLEX_KEY}}
    - Jellyfin:
        href: https://jellyfin.sheetgenius.app
        icon: jellyfin.svg
        description: jellyfin-prod-1 on rpi-angel-1
        # widget:
        #     type: jellyfin
        #     url: https://jellyfin.sheetgenius.app
        #     key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
    - Torrent:
        - Sonarr:
            href: https://sonarr.sheetgenius.app
            icon: sonarr.svg
            description: sonarr-prod-1 on rpi-angel-1
            # widget:
            #     type: sonarr
            #     url: https://sonarr.sheetgenius.app
            #     key: {{HOMEPAGE_VAR_SONARR_KEY}}
        - Radarr:
            href: https://radarr.sheetgenius.app
            icon: radarr.svg
            description: radarr-prod-1 on rpi-angel-1
            # widget:
            #     type: radarr
            #     url: https://radarr.sheetgenius.app
            #     key: {{HOMEPAGE_VAR_RADARR_KEY}}
        - Lidarr:
            href: https://lidarr.sheetgenius.app
            icon: lidarr.svg
            description: lidarr-prod-1 on rpi-angel-1
            # widget:
            #     type: lidarr
            #     url: https://lidarr.sheetgenius.app
            #     key: {{HOMEPAGE_VAR_LIDARR_KEY}}
        - Readarr:
            href: https://readarr.sheetgenius.app
            icon: readarr.svg
            description: readarr-prod-1 on rpi-angel-1
            # widget:
            #     type: readarr
            #     url: https://readarr.sheetgenius.app
            #     key: {{HOMEPAGE_VAR_READARR_KEY}}
        - Bazarr:
            href: https://bazarr.sheetgenius.app
            icon: bazarr.svg
            description: bazarr-prod-1 on rpi-angel-1
            # widget:
            #     type: bazarr
            #     url: https://bazarr.sheetgenius.app
            #     key: {{HOMEPAGE_VAR_BAZARR_KEY}}
        - Bittorrent:
            href: https://bittorrent.sheetgenius.app
            icon: si-bittorrent
            description: bittorrent-prod-1 on rpi-angel-1
            # widget:
            #     type: bittorrent
            #     url: https://bittorrent.sheetgenius.app
            #     key: {{HOMEPAGE_VAR_BITTORRENT_KEY}}
