---
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
        timeStyle: short
        hourCycle: h23

- openmeteo:
    label: Lenzburg # optional
    latitude: 47.3885
    longitude: 8.175
    timezone: Europe/Zurich # optional
    units: metric
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1