# Homepage configuration

title: "Homelab"
subtitle: "heimdall"
logo: "assets/tools/homer.svg"

header: true
footer: '<p>Made with <i class="fas fa-heart"></i> by ansasi.</p>'

# columns: "3"
connectivityCheck: true

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#2E3440"
    highlight-secondary: "#4C566A"
    highlight-hover: "#81A1C1"
    background: "#3B4252"
    card-background: "#2E3440"
    text: "#D8DEE9"
    text-header: "#D8DEE9"
    text-title: "#81A1C1"
    text-subtitle: "#81A1C1"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#BF616A"

# Optional navbar
links:
  - name: "GitHub Repo"
    icon: "fab fa-github"
    url: "https://github.com/ansasi/docker_home_server"
    target: "_blank"

# Services
services:
  - name: "Media"
    icon: "fas fa-film"
    items:
      - name: "Plex Media Server"
        logo: "assets/tools/plex.svg"
        subtitle: "Stream Movies & TV Shows"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:32400"
        target: "_blank"

      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.svg"
        subtitle: "Stream Movies & TV Shows"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:8096"
        target: "_blank"

      - name: "Photoprism"
        logo: "assets/tools/photoprism.svg"
        subtitle: "Photo storage at home"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:2342"
        target: "_blank"

  - name: "File Storage & Sharing"
    icon: "fas fa-folder"
    items:
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.svg"
        subtitle: "File hosting at home"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:8008"
        target: "_blank"

      - name: "Bittorrent"
        logo: "assets/tools/qbittorrent.svg"
        subtitle: "Bittorrent client"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:9091"
        target: "_blank"

  - name: "Monitoring"
    icon: "fas fa-desktop"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.svg"
        subtitle: "Monitoring tool"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:61208"
        target: "_blank"

  - name: "Automation"
    icon: "fas fa-cogs"
    items:
      - name: "Home Assistant"
        logo: "assets/tools/homeassistant.svg"
        subtitle: "Home automation"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:8123"
        target: "_blank"

  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Portainer"
        logo: "assets/tools/portainer.svg"
        subtitle: "Docker Container Management"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:9000"
        type: "Portainer"
        apikey: "{{ portainer_api_key }}"
      
      - name: "Pihole"
        logo: "assets/tools/pihole.svg"
        subtitle: "Ad-Blocker"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}"
        target: "_blank"

      - name: "Wireguard"
        logo: "assets/tools/wireguard.svg"
        subtitle: "VPN"
        url: "http://{{ ansible_hostname }}.{{ domain_name }}:51820"
        target: "_blank"

  - name: "Cluster"
    icon: "fas fa-network-wired"
    items:
      - name: "{{ nas.hostname }}"
        icon: "fas fa-database"
        url: "http://{{ nas.hostname }}.{{ domain_name}}"
        tag: "nas"
