---
# This is the main playbook for the Raspberry Pi Home Server
# Basic setup
- name: Update the system
  hosts: all
  become: yes
  roles:
    - update

- name: Install Docker
  hosts: all
  become: yes
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - pi

- name: Create Docker network
  hosts: all
  become: yes
  tasks:
    - name: Create Docker network
      docker_network:
        name: proxy
        state: present
        driver: bridge

- name: Download Git repository https://github.com/ansasi/docker_home_server.git
  hosts: all
  become: yes
  tasks:
    - name: Download Git repository
      git:
        repo: "https://github.com/ansasi/docker_home_server.git"
        dest: "/home/pi/docker_home_server"
        update: yes
        version: develop # TODO: Change to master

# Docker Apps
# PiHole Requirements
# For Ubuntu Installation:
# 1. disable DNSStubListener=yes in /etc/systemd/resolved.conf
# 2. sudo systemctl restart systemd-resolved
- name: Disable systemd-resolved DNSStubListener
  hosts: dns
  become: yes
  tasks:
    - name: Disable systemd-resolved DNSStubListener
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=no'
      notify: Restart systemd-resolved
  
  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted


- name: Install PiHole
  hosts: dns
  become: yes
  roles:
    - docker_compose_deploy
  vars:
    docker_compose_src: "/home/pi/docker_home_server/docker-apps/networking/pihole/"

- name: Install Traefik
  hosts: angel
  become: yes
  roles:
    - docker_compose_deploy
  vars:
    docker_compose_src: "/home/pi/docker_home_server/docker-apps/networking/traefik/"

- name: Install Portainer
  hosts: all
  become: yes
  roles:
    - docker_compose_deploy
  vars:
    docker_compose_src: "/home/pi/docker_home_server/docker-apps/management/portainer/"

- name: Install Homepage
  hosts: angel
  become: yes
  roles:
    - docker_compose_deploy
  vars:
    docker_compose_src: "/home/pi/docker_home_server/docker-apps/management/homepage/"
