---
networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus-http.entrypoints=web
      - traefik.http.routers.prometheus-http.rule=Host(`prometheus.sheetgenius.app`)
      - traefik.http.routers.prometheus-https.entrypoints=websecure
      - traefik.http.routers.prometheus-https.rule=Host(`prometheus.sheetgenius.app`)
      - traefik.http.routers.prometheus-https.tls=true
      - traefik.http.routers.prometheus-https.tls.certresolver=cloudflare
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    restart: unless-stopped
