---
networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.sheetgenius.app`)"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.certresolver=cloudflare"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    restart: unless-stopped
