---
networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # TODO: Replace with a secure password
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana-http.entrypoints=web
      - traefik.http.routers.grafana-http.rule=Host(`grafana.sheetgenius.app`)
      - traefik.http.routers.grafana-https.entrypoints=websecure
      - traefik.http.routers.grafana-https.rule=Host(`grafana.sheetgenius.app`)
      - traefik.http.routers.grafana-https.tls=true
      - traefik.http.routers.grafana-https.tls.certresolver=cloudflare
    restart: unless-stopped